### ISSUE TITLE
Customize CSS not working after the latest update 0.5.8

### ISSUE THREAD

**Issue by Magolor** [shd101wyy/vscode-markdown-preview-enhanced#356]
After updating to 0.5.8, the customized CSS in .mume/style.less stopped working.

**Comment by shd101wyy** [comment]
Thanks for reporting the issue. I will take a look soon.

**Comment by shd101wyy** [comment]
Should be fixed in `0.5.9`. Thank you.

**Comment by Magolor** [comment]
Actually some problems still unfixed about customize CSS.

To adjust the size of an imported image, I added this in customized CSS:
```
.markdown-preview img[src*='?20h']{
  height: 20rem;
}
```

Thus when importing images, I can easily write in markdown:
```
![](img.png?20h)
```

However, after repeatedly trying. I found the same piece of code works under 0.5.3 but not 0.5.9.

Please fix it or tell me how to fix my code in order to adapt a new grammar (maybe?).

Thank you very much!
